### PR TITLE
made a storage package Skeleton

### PR DESCRIPTION
**Pull request by technomooney**
just making it so main has a decent structure to be built upon.

### CODE REVIEW

**Comment by natalie-pratt** [comment]
@technomooney looks good!

**Comment by technomooney** [comment]
@natalie-pratt please use the review function for this otherwise i cant merge
thanks!

**Review by natalie-pratt — APPROVED** [review]
So sorry about not using this before - looks good!

**Comment by natalie-pratt** [comment]
Pull request irrelevant now - wasn't merged in time to be used.

**Pull request closed without merging**
