### PR TITLE
Started working on NPS api. 

### PR DESCRIPTION
**Pull request by technomooney**
@oscar-chiqui  is taking over this module. 
goals are on issue #11

### CODE REVIEW

**Comment by MCTCJulesO** [comment]
This looks good so far!

**Comment by natalie-pratt** [comment]
I think that maybe just the one function shouldn't be doing all the work. Maybe separate the portion that does the request and the portion that creates the Park object?

**Comment by technomooney** [comment]
I can help make the models and such when I get the chance... I'll be working on it while I'm on the road this weekend.

**Review by natalie-pratt — CHANGES_REQUESTED** [review]
Sorry about not using the review function before. Can we separate the API call and the data processing into different functions to ensure easy testing and modular code?

**Comment by technomooney** [comment]
closed to reduce confusion

**Pull request closed without merging**
