### PR TITLE
Web UI setup

### PR DESCRIPTION
**Pull request by technomooney**
Just setup a basic flask app to act as the web ui. there is nothing designed yet... we need to figure out more stuff before i can set that with more detail. let me know if there are any suggestions.

### CODE REVIEW

**Comment by technomooney** [comment]
this is a start for issue #2 i think i want to remove pr #5  and use this as the "solution" for #2 

@natalie-pratt let me know if i can close this without merging.

**Comment by natalie-pratt** [comment]
@technomooney this looks good! You can close without merging.

**Comment by technomooney** [comment]
> @technomooney this looks good! You can close without merging.

@natalie-pratt  Close _without_ merging???

**Comment by technomooney** [comment]
> > @technomooney this looks good! You can close without merging.
> 
> @natalie-pratt Close _without_ merging???

oooh ok close the pr#5

**Comment by natalie-pratt** [comment]
@technomooney I'm talking about your question that you asked about the issue

**Comment by natalie-pratt** [comment]
> this is a start for issue #2 i think i want to remove pr #5 and use this as the "solution" for #2
> 
> @natalie-pratt let me know if i can close this without merging.

@technomooney

**Pull request merged**
