### PR TITLE
Creating the README file

### PR DESCRIPTION
**Pull request by MCTCJulesO**
I have started the README file, I will finish it as we have screenshots etc.

### CODE REVIEW

**Review by natalie-pratt — COMMENTED** [review]
Looking good so far!

**Review by jk3132kv — APPROVED** [review]

**Comment by oscar-chiqui** [comment]
the Readme has duplicate information, I did some changes check out: 
**Installation:**

1. Clone the repository: git clone https://github.com/technomooney/Project-3-API-and-bookmarks

2. Navigate to the project directory: cd Project-3-API-and-bookmarks

3. Install the required dependencies: pip install -r requirements.txt

Usage:

1. Run the national_park_searcher.py script in a Python environment: python national_park_searcher.py

2. Enter the name of a national park you are interested in and press Enter.

3. The application will display a list of national parks that match your search query.

4. Select a park from the list by entering its corresponding number and pressing Enter.

5. The application will display more detailed information about the selected park, including its park code, latitude, longitude, phone number, email, description, image, and current forecast.

**Comment by MCTCJulesO** [comment]
@oscar-chiqui What duplicate information is this fixing?

**Review by natalie-pratt — APPROVED** [review]
Looks good

**Pull request merged**
